import { FormControl, Input, InputLabel, Button } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';


export default function Signup({ roomId,setUserName,setName }) {
   const [Name, SetNName] = useState("");
   const [UserName, Setusername] = useState("")
    const [room, setRoom] = useState(""); 
    const navigate = useNavigate();


    
    // Function to handle creating a new room by host
    function handleCreateRoom() {
        const Host = {
            Name: Name,
            Host: true,
            RoomID: roomId
        };

        // Navigate to the room created by the host
        setName(Host)
        navigate(`/${roomId}`,{ state: { Host: true, Name: Name, RoomID: roomId } });
        console.log("Host created room:", Host);
    }

    // Function to handle joining a room by a guest
    function handleJoinRoom() {
        const user = {
            Name: UserName,
            Host: false,
            RoomID: room   // Using the room entered by the user
        };

        // Navigate to the room entered by the user
        navigate(`/${room}`,{ state: { Host: false, Name: UserName, RoomID: room } });
        console.log("User joining room:", user);
    }

    return (
        <div style={{ display: "flex", width: "95vw", padding: "1rem", justifyContent: "center" }}>

            {/*  Form for Signup (Create Room) */}
            <div >
                <h2 style={{ textAlign: "center",color:"white" }}>Create Chat Room</h2>
                <form style={{ display: "flex", backgroundColor:"white", flexDirection: "column", border: "1.5px solid black", padding: "1.5rem", borderRadius: "8px", width: "35vw" }}>
                    <FormControl>
                        <InputLabel>Name</InputLabel>
                        <Input
                            id='my-input'
                            placeholder='Write Your Name'
                            aria-describedby="my-helper-text"
                            type='text'
                            onChange={(e) => SetNName(e.target.value)}
                        />
                    </FormControl>
                    <FormControl sx={{ marginTop: "3%" }}>
                        <Input
                            id='my-input'
                            value={roomId}  // Display the room ID generated by the app
                            placeholder='Your Room ID'
                            aria-describedby="my-helper-text"
                            type='text'
                            readOnly
                        />
                      
                    </FormControl>
                    <FormControl sx={{ marginTop: "3%" }}>
                        <Button variant='outlined' onClick={handleCreateRoom}>Submit</Button>
                    </FormControl>
                </form>
            </div>

            {/* Form for Login (Join Room) */}
            <div>
                <h2 style={{ textAlign: "center",color:"white" }}>Join Chat Room</h2>
                <form style={{ display: "flex",backgroundColor:"white",flexDirection: "column", border: "1.5px solid black", padding: "1.5rem", borderRadius: "8px", width: "35vw", marginLeft: "2rem" }}>
                    <FormControl>
                        <InputLabel>Name</InputLabel>
                        <Input
                            id='my-input'
                            placeholder='Write Your Name'
                            aria-describedby="my-helper-text"
                            type='text'
                            onChange={(e) => Setusername(e.target.value)}
                        />
                    </FormControl>
                    <FormControl sx={{ marginTop: "3%" }}>
                        <InputLabel>Chat Room ID</InputLabel>
                        <Input
                            id='my-input'
                            placeholder='Enter Room ID'
                            aria-describedby="my-helper-text"
                            type='text'
                            onChange={(e) => setRoom(e.target.value)}   // Set the room value entered by the user
                        />
                    </FormControl>
                    <FormControl sx={{ marginTop: "3%" }}>
                        <Button variant='outlined' onClick={handleJoinRoom}>Submit</Button>
                    </FormControl>
                </form>
            </div>
        </div>
    )
}
